baseURL: "https://kisnikser.github.io/"
languageCode: en-us
title: Nikita Kiselev
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  keywords: [CV, Portfolio, Machine Learning]
  author: Nikita Kiselev
  DateFormat: "January 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  math: true

  profileMode:
    enabled: true
    subtitle: "Data Scientist, Optimization Researcher"
    imageUrl: "images/photo.jpg"
    imageWidth: 240
    imageHeight: 240
    imageTitle: "Nikita Kiselev"
    buttons:
      - name: Publications
        url: publications
      - name: Talks
        url: talks

  socialIcons:
    - name: telegram
      url: "https://t.me/kisnikser"
    - name: email
      url: "mailto:kiselev.ns@phystech.su"
    - name: github
      url: "https://github.com/kisnikser"
    - name: linkedin
      url: "https://www.linkedin.com/in/kisnikser"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: false

  editPost:
    URL: ""
    Text: ""
    appendFilePath: true

menu:
  main:
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 1
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 2
    - identifier: talks
      name: Talks
      url: /talks/
      weight: 3
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 4
    - identifier: awards
      name: Awards
      url: /awards/
      weight: 5
    - identifier: resume
      name: Resume
      url: https://texlive2020.latexonline.cc/compile?git=https://github.com/kisnikser/CV&target=resume.tex&command=pdflatex
      weight: 6
    - identifier: cv
      name: CV
      url: https://texlive2020.latexonline.cc/compile?git=https://github.com/kisnikser/CV&target=cv.tex&command=pdflatex
      weight: 7