baseURL: "https://kisnikser.github.io/" 
title: Nikita Kiselev
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Resume
          url: resume.pdf
          weight: 4
        - name: CV
          url: cv.pdf
          weight: 5
        - name: Tags
          url: tags/
          weight: 6
        - name: Archive
          url: archive/
          weight: 7

params:
    description: "I am a master's student in Computer Science in the Intelligent Systems Department at Moscow Institute of Physics and Technology. 
    My research focuses mostly on Generative AI, Computer Vision, and Optimization."
    author: Nikita Kiselev
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","talks","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nikita Kiselev
          subtitle: "**Data Scientist, Optimization Researcher**\n> 

          I am a master's student in Computer Science in the Intelligent Systems Department 
          at Moscow Institute of Physics and Technology.
          Prior to that, I received my bachelor's degree in Applied Mathematics and Physics there.\n>
          
          Currently, I am a research intern at Sber AI
          and mathematician-programmer at Center for Artificial Intelligence, Innopolis University.\n>

          My research interests include Generative AI, Computer Vision, and Optimization."
          imageUrl: "photo.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Talks
              url: talks/
            - name: Projects
              url: projects/
            - name: Resume
              url: resume.pdf
            - name: CV
              url: cv.pdf

    socialIcons:
        - name: telegram
          url: https://t.me/kisnikser
        - name: email
          url: kiselev.ns@phystech.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=8BOqs70AAAAJ&hl=ru
        - name: github
          url: https://github.com/kisnikser
        - name: linkedin
          url: https://www.linkedin.com/in/kisnikser

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nikita Kiselev"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2